### ISSUE TITLE
mkdir not a directory error

### ISSUE THREAD

**Issue by towerofnix** [lightblub/nearley-make#1]
@Jonathan50 [got this error](https://scratch.mit.edu/users/liam48D/#comments-25471809) when testing [my project](https://github.com/liam4/aterscriptisfakescriptlolscript) - I'm 90% sure it has to do with `nearley-make`:

> ```
> ENOTDIR: not a directory, mkdir '~/.npm/nearley/2.7.1/package'
> ```

**Comment by bates64** [comment]
This package never tries to make a directory

**Comment by towerofnix** [comment]
"cannot reproduce" - if you clone my repository and test will it have the issue..?

(I guess I need to test it myself! ^^;)

EDIT: I can't reproduce this either... hm..

**Comment by jeandrek** [comment]
Wait what, it's right, ~/.npm/nearley is a file...

**Comment by jeandrek** [comment]
Deleting ~/.npm/nearley seems to fix it.

**Comment by towerofnix** [comment]
Closing for now.. if it comes up again we can re-open the issue.
