### ISSUE TITLE
Make it nearley-made instead of nearley-make

### ISSUE THREAD

**Issue by towerofnix** [lightblub/nearley-make#2]
Let's get the official thumb up/downs going!!!!!!!

It sounds better.

**Comment by bates64** [comment]
but what about projects that depend on `npm/nearley-make`

**Comment by towerofnix** [comment]
I'd be shocked if NPM doesn't have a way to deal with repo-name-changes..
_looks_

EDIT: Yay, [there isn't](http://stackoverflow.com/questions/28371669/renaming-a-published-npm-module). :tada:
