### ISSUE TITLE
require(...) inside grammar breaks evaluating the generated code

### ISSUE THREAD

**Issue by ManuelOverdijk** [lightblub/nearley-make#3]
Any require('myFile.js') inside a defined grammar seems to break nearley-make on line 37 with
`TypeError: require is not a function at eval`.

```
grammar = (new Function(...argKeys, genned))(...argValues)
```

**Comment by freddi301** [comment]
ok i had the same issue
here how to solve

```javascript
var make = require('nearley-make');
var parser = make('my fancy language', { require: require });
parser.feed(text);
console.log(parser.results);
```

@lightblub clever work with the `new Function` hack, consider adding in the usage example argumetns the require

**Comment by ManuelOverdijk** [comment]
Nice workaround, would've saved me some effort. I worked around this by not including the require calls, and adding them after I parsed my grammar
